/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adi.thinkoop.perwalianonline.view;

import com.adi.thinkoop.perwalianonline.controller.DetailMatakuliahController;
import com.adi.thinkoop.perwalianonline.model.DetailMatakuliah;
import com.adi.thinkoop.perwalianonline.model.Matakuliah;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author adi nuralim
 */
public final class DetailMatakuliahDialog extends javax.swing.JDialog {

    private static Matakuliah matakuliah;
    /**
     * Creates new form KontrakDialog
     */
    private static DetailMatakuliahDialog detailMatakuliahDialog;

    public static DetailMatakuliahDialog getInstance(Matakuliah matakuliah) {

        DetailMatakuliahDialog.matakuliah = matakuliah;

        if (detailMatakuliahDialog == null) {
            detailMatakuliahDialog = new DetailMatakuliahDialog(MainFrame.getInstance(), true);
        }

        detailMatakuliahDialog.populateTableDetailMatakuliah();
        return detailMatakuliahDialog;
    }

    public DetailMatakuliahDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateColumnModel();


    }

    void populateColumnModel() {
        TableColumnModel tableColumnModel = tabelDetailMk.getColumnModel();
        TableColumn tableColumn = tableColumnModel.getColumn(0);
        TableColumn tableColumn1 = tableColumnModel.getColumn(1);
        TableColumn tableColumn2 = tableColumnModel.getColumn(2);
        TableColumn tableColumn3 = tableColumnModel.getColumn(3);
        TableColumn tableColumn4 = tableColumnModel.getColumn(4);

        tableColumn.setMaxWidth(40);
        tableColumn1.setMaxWidth(50);
        tableColumn3.setMaxWidth(80);
        tableColumn4.setMaxWidth(80);


    }

    void populateTableDetailMatakuliah() {

        textKodeMk.setText(DetailMatakuliahDialog.matakuliah.getKodeMk());
        textMatakuliah.setText(DetailMatakuliahDialog.matakuliah.getMatakuliah());
        textSks.setText(String.valueOf(DetailMatakuliahDialog.matakuliah.getSks()));
        new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {

                DefaultTableModel defaultTableModel = (DefaultTableModel) tabelDetailMk.getModel();
                defaultTableModel.setRowCount(0);


                for (Map.Entry<Integer, DetailMatakuliah> entry : DetailMatakuliahDialog.matakuliah.getDetailMatakuliahs().entrySet()) {
                    Integer integer = entry.getKey();
                    DetailMatakuliah detailMatakuliah = entry.getValue();
                    int kontrakMk = DetailMatakuliahController.getInstance().getJumlahKontrakDetailMatakuliah(detailMatakuliah);
                    defaultTableModel.addRow(new Object[]{defaultTableModel.getRowCount() + 1, detailMatakuliah.getKelas(), detailMatakuliah.getDosen(), kontrakMk, detailMatakuliah.getKapasitas()});
                }
                tabelDetailMk.setModel(defaultTableModel);
                return null;
            }
        }.execute();
    }

    public JTable getTabelDetailMk() {
        return tabelDetailMk;
    }

    public JLabel getTextKodeMk() {
        return textKodeMk;
    }

    public JLabel getTextMatakuliah() {
        return textMatakuliah;
    }

    public JLabel getTextSks() {
        return textSks;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDetailMk = new javax.swing.JTable();
        buttonKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textKodeMk = new javax.swing.JLabel();
        textMatakuliah = new javax.swing.JLabel();
        textSks = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelDetailMk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelDetailMk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kelas", "Dosen", "Terisi", "Kapasitas"
            }
        ));
        jScrollPane1.setViewportView(tabelDetailMk);

        buttonKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("KODE MK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MATAKULIAH");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("SKS");

        textKodeMk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textKodeMk.setText("KODE MK");

        textMatakuliah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textMatakuliah.setText("MATAKULIAH");

        textSks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textSks.setText("SKS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonKembali)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMatakuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(textSks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textKodeMk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textKodeMk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(textMatakuliah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(textSks))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonKembali)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-379)/2, 646, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailMatakuliahDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                DetailMatakuliahDialog dialog = new DetailMatakuliahDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelDetailMk;
    private javax.swing.JLabel textKodeMk;
    private javax.swing.JLabel textMatakuliah;
    private javax.swing.JLabel textSks;
    // End of variables declaration//GEN-END:variables
}
