/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adi.thinkoop.perwalianonline.view;

import com.adi.thinkoop.perwalianonline.controller.KontrakMatakuliahController;
import com.adi.thinkoop.perwalianonline.controller.LoginController;
import com.adi.thinkoop.perwalianonline.controller.MahasiswaController;
import com.adi.thinkoop.perwalianonline.controller.PerwalianController;
import com.adi.thinkoop.perwalianonline.launcher.SplashLauncher;
import java.util.logging.Level;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author adi nuralim
 */
public final class KontrakDialog extends javax.swing.JDialog {

    /**
     * Creates new form KontrakDialog
     */
    private static KontrakDialog kontrakDialog;

    public static KontrakDialog getInstance(boolean b) {
        if (kontrakDialog == null) {
            kontrakDialog = new KontrakDialog(MainFrame.getInstance(), true);
        }

        if (b) {
            KontrakMatakuliahController.getInstance().populateTableKontrakMatakuliah();
        }

        return kontrakDialog;
    }

    public KontrakDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();


        populateColumnModel();
    }

    void populateColumnModel() {
        TableColumnModel tableColumnModel = tabelKontrakMatakuliah.getColumnModel();
        TableColumn tableColumn = tableColumnModel.getColumn(0);
        TableColumn tableColumn1 = tableColumnModel.getColumn(1);
        TableColumn tableColumn2 = tableColumnModel.getColumn(2);
        TableColumn tableColumn4 = tableColumnModel.getColumn(4);
        TableColumn tableColumn5 = tableColumnModel.getColumn(5);
        TableColumn tableColumn6 = tableColumnModel.getColumn(6);
        TableColumn tableColumn7 = tableColumnModel.getColumn(7);
        tableColumn.setMaxWidth(40);
        tableColumn1.setMaxWidth(60);
        tableColumn2.setMaxWidth(40);
        tableColumn4.setMaxWidth(40);
        tableColumn5.setMaxWidth(40);
        tableColumn6.setMaxWidth(80);
        tableColumn7.setMaxWidth(40);
    }

    public JTable getTabelKontrakMatakuliah() {
        return tabelKontrakMatakuliah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKontrakMatakuliah = new javax.swing.JTable();
        buttonKontrakMatakuliah = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelKontrakMatakuliah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelKontrakMatakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kontrak", "Kode", "Matakuliah", "Kelas", "Terisi", "Kapasitas", "Sks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelKontrakMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelKontrakMatakuliahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelKontrakMatakuliahMouseReleased(evt);
            }
        });
        tabelKontrakMatakuliah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelKontrakMatakuliahKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKontrakMatakuliah);

        buttonKontrakMatakuliah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKontrakMatakuliah.setText("Kontrak Matakuliah");
        buttonKontrakMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKontrakMatakuliahActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonBatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonKontrakMatakuliah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBatal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKontrakMatakuliah)
                    .addComponent(buttonReset)
                    .addComponent(buttonBatal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-561)/2, 646, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        KontrakMatakuliahController.getInstance().reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonKontrakMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKontrakMatakuliahActionPerformed
        // TODO add your handling code here:
        PerwalianController.getInstance().simpanPerwalian();
    }//GEN-LAST:event_buttonKontrakMatakuliahActionPerformed

    private void tabelKontrakMatakuliahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKontrakMatakuliahKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKontrakMatakuliahKeyPressed

    private void tabelKontrakMatakuliahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKontrakMatakuliahMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKontrakMatakuliahMousePressed

    private void tabelKontrakMatakuliahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKontrakMatakuliahMouseReleased
        // TODO add your handling code here:

        int totalSks;
        try {
            totalSks = Integer.valueOf(MainFrame.getInstance().getTextTotalSks().getText());
        } catch (NumberFormatException numberFormatException) {
            SplashLauncher.logger.log(Level.SEVERE, null, numberFormatException);
            totalSks = 0;
        }

        int tempSks = totalSks;
        DefaultTableModel defaultTableModel = (DefaultTableModel) tabelKontrakMatakuliah.getModel();
        int row = tabelKontrakMatakuliah.getRowCount();
        for (int i = 0; i < row; i++) {
            boolean kontrak = (boolean) defaultTableModel.getValueAt(i, 1);
            if (kontrak) {
                tempSks = tempSks + Integer.valueOf(defaultTableModel.getValueAt(i, 7).toString());
            }
        }


        int max = MahasiswaController.getInstance().getMax(MahasiswaController.getInstance().getIps(LoginController.getInstance().getMahasiswa()));


        if (tempSks > max) {
            buttonKontrakMatakuliah.setEnabled(false);
        } else {
            buttonKontrakMatakuliah.setEnabled(true);
        }
    }//GEN-LAST:event_tabelKontrakMatakuliahMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontrakDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                KontrakDialog dialog = new KontrakDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonKontrakMatakuliah;
    private javax.swing.JButton buttonReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKontrakMatakuliah;
    // End of variables declaration//GEN-END:variables
}
