/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adi.thinkoop.perwalianonline.view;


import com.adi.thinkoop.perwalianonline.controller.*;
import com.adi.thinkoop.perwalianonline.launcher.SplashLauncher;
import com.adi.thinkoop.perwalianonline.model.Matakuliah;
import com.adi.thinkoop.perwalianonline.utils.Message;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author adi nuralim
 */
public final class MainFrame extends javax.swing.JFrame {

    private static MainFrame mainFrame;
    private boolean bMasuk = false;
    private Dimension dimension;

    public static MainFrame getInstance() {
        if (mainFrame == null) {
            mainFrame = new MainFrame();
        }

        return mainFrame;
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(dimension.width, dimension.height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        //--------------------------

        populateComponent(true);
        populateColumnModel();
    }

    void populateComponent(boolean b) {
        masukMenuItem.setEnabled(b);
        keluarMenuItem.setEnabled(!b);
        tutupMenuItem.setEnabled(b);

    }

    void populateColumnModel() {
        TableColumnModel tableColumnModel = tabelKrs.getColumnModel();
        TableColumn tableColumn = tableColumnModel.getColumn(0);
        TableColumn tableColumn1 = tableColumnModel.getColumn(1);
        TableColumn tableColumn3 = tableColumnModel.getColumn(3);
        TableColumn tableColumn4 = tableColumnModel.getColumn(4);
        tableColumn.setMaxWidth(40);
        tableColumn1.setMaxWidth(60);
        tableColumn3.setMaxWidth(150);
        tableColumn4.setMaxWidth(40);

        //-------------------------------------------------------
        TableColumnModel tableColumnModel1 = tabelMatakuliah.getColumnModel();
        TableColumn tc = tableColumnModel1.getColumn(0);
        TableColumn tc1 = tableColumnModel1.getColumn(1);
        TableColumn tc3 = tableColumnModel1.getColumn(3);
        tc.setMaxWidth(40);
        tc1.setMaxWidth(60);
        tc3.setMaxWidth(60);

    }

    void masuk() {
        if (LoginController.getInstance().cekLogin()) {

            ((CardLayout) content.getLayout()).show(content, "PENGELOLAAN");
            tabPerwalian.setSelectedIndex(0);
            populateComponent(false);
            Message.getInstance(this).runMessage("login berhasil!");
        } else {
            Message.getInstance(this).runErrorMessage("NPM dan Sandi tidak sesuai!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        basedPanel = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        masuk = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        textSandi = new javax.swing.JPasswordField();
        buttonMasuk = new javax.swing.JButton();
        buttonBersihkan = new javax.swing.JButton();
        pengelolaan = new javax.swing.JPanel();
        tabPerwalian = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNpm = new javax.swing.JLabel();
        textNama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textIpk = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textProgram = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textProdi = new javax.swing.JLabel();
        textDosenWali = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        comboTahunAkademikKrs = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textNpmKrs1 = new javax.swing.JLabel();
        buttonCariKrs = new javax.swing.JButton();
        buttonResetKrs = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        textNpmKrs = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textNamaKrs = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textProgramKrs = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        textProdiKrs = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        textIpsKrs = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        textIpkKrs = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        totalSksMahasiswa = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        textDosenKrs = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        textStatus = new javax.swing.JLabel();
        buttonCetakKrs = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        totalSksMahasiswa1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        textDosenKrs1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKrs = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        textTotalSks = new javax.swing.JLabel();
        buttonMundur = new javax.swing.JButton();
        buttonKontrakMatakuliah = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMatakuliah = new javax.swing.JTable();
        buttonRinci = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        textPesanDosenWali = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textPesan = new javax.swing.JTextArea();
        buttonKirim = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelPesanMasuk = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        textPesanMasuk = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelPesanTerkirim = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        textPesanTerkirim = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        masukMenuItem = new javax.swing.JMenuItem();
        keluarMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        tutupMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perwalian Online");

        content.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        content.setLayout(new java.awt.CardLayout());

        home.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aplikasi Perwalian Online");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 455;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(189, 10, 244, 10);
        home.add(jLabel4, gridBagConstraints);

        content.add(home, "HOME");

        masuk.setLayout(new java.awt.GridBagLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("NPM");

        textUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Sandi");

        textSandi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textSandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSandiActionPerformed(evt);
            }
        });

        buttonMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonMasuk.setText("Masuk");
        buttonMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMasukActionPerformed(evt);
            }
        });

        buttonBersihkan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonBersihkan.setText("Reset");
        buttonBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textUsername))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textSandi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addComponent(buttonBersihkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMasuk)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel44)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel45)
                    .addComponent(textSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMasuk)
                    .addComponent(buttonBersihkan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(156, 278, 250, 187);
        masuk.add(jPanel19, gridBagConstraints);

        content.add(masuk, "MASUK");

        tabPerwalian.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 17))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("NPM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText(":");

        textNpm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textNpm.setText("NPM");

        textNama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textNama.setText("NAMA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("NAMA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText(":");

        textIpk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textIpk.setText("IPK");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("IPS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("PROGRAM");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText(":");

        textProgram.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textProgram.setText("PROGRAM");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("PRODI");

        textProdi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textProdi.setText("PRODI");

        textDosenWali.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textDosenWali.setText("DOSEN WALI");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("DOSEN WALI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textProdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textDosenWali, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNpm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textIpk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(textNpm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(textNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(textIpk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(textProgram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(textProdi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(textDosenWali))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPerwalian.addTab("Data Diri", jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("TAHUN AKADEMIK");

        comboTahunAkademikKrs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboTahunAkademikKrs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTahunAkademikKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTahunAkademikKrsActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("NPM");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText(":");

        textNpmKrs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textNpmKrs1.setText("NPM");

        buttonCariKrs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonCariKrs.setText("Cari");
        buttonCariKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariKrsActionPerformed(evt);
            }
        });

        buttonResetKrs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonResetKrs.setText("Reset");
        buttonResetKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetKrsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTahunAkademikKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(textNpmKrs1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCariKrs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonResetKrs)
                .addGap(1, 1, 1))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboTahunAkademikKrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(textNpmKrs1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonCariKrs)
                .addComponent(buttonResetKrs))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("NPM");
        jPanel9.add(jLabel23);

        textNpmKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textNpmKrs.setText("NPM");
        jPanel9.add(textNpmKrs);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("NAMA");
        jPanel9.add(jLabel26);

        textNamaKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textNamaKrs.setText("NAMA");
        jPanel9.add(textNamaKrs);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("PROGRAM");
        jPanel9.add(jLabel29);

        textProgramKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textProgramKrs.setText("PROGRAM");
        jPanel9.add(textProgramKrs);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("PRODI");
        jPanel9.add(jLabel24);

        textProdiKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textProdiKrs.setText("PRODI");
        jPanel9.add(textProdiKrs);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("IPS");
        jPanel11.add(jLabel30);

        textIpsKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textIpsKrs.setText("IPS");
        jPanel11.add(textIpsKrs);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("IPK");
        jPanel11.add(jLabel31);

        textIpkKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textIpkKrs.setText("IPK");
        jPanel11.add(textIpkKrs);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("TOTAL SKS");
        jPanel11.add(jLabel32);

        totalSksMahasiswa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSksMahasiswa.setText("TOTAL SKS");
        jPanel11.add(totalSksMahasiswa);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("DOSEN WALI");
        jPanel11.add(jLabel33);

        textDosenKrs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textDosenKrs.setText("DOSEN WALI");
        jPanel11.add(textDosenKrs);

        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("STATUS");
        jPanel20.add(jLabel34);

        textStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textStatus.setText("STATUS");
        jPanel20.add(textStatus);

        buttonCetakKrs.setText("CETAK KRS");
        buttonCetakKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakKrsActionPerformed(evt);
            }
        });
        jPanel20.add(buttonCetakKrs);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel20.add(jLabel35);

        totalSksMahasiswa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel20.add(totalSksMahasiswa1);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel20.add(jLabel37);

        textDosenKrs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel20.add(textDosenKrs1);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel20.add(jLabel38);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabelKrs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode MK", "Matakuliah", "Status", "Kelas", "SKS"
            }
        ));
        jScrollPane1.setViewportView(tabelKrs);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("TOTAL SKS");

        textTotalSks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textTotalSks.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textTotalSks.setText("SKS");

        buttonMundur.setText("MUNDUR");
        buttonMundur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMundurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textTotalSks, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonMundur)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMundur)
                    .addComponent(textTotalSks)
                    .addComponent(jLabel39))
                .addContainerGap())
        );

        buttonKontrakMatakuliah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKontrakMatakuliah.setText("Kontrak Matakuliah");
        buttonKontrakMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKontrakMatakuliahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(buttonKontrakMatakuliah)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonKontrakMatakuliah)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPerwalian.addTab("Daftar KRS", jPanel2);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tabelMatakuliah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelMatakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode MK", "Matakuliah", "SKS"
            }
        ));
        jScrollPane2.setViewportView(tabelMatakuliah);

        buttonRinci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonRinci.setText("Detail Matakuliah");
        buttonRinci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRinciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonRinci)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRinci)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPerwalian.addTab("Daftar Matakuliah", jPanel3);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("KEPADA");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText(":");

        textPesanDosenWali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textPesanDosenWali.setText("DOSEN WALI");

        textPesan.setColumns(20);
        textPesan.setRows(5);
        jScrollPane3.setViewportView(textPesan);

        buttonKirim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonKirim.setText("Kirim");
        buttonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKirimActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPesanDosenWali, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonKirim)))
                        .addContainerGap())))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(textPesanDosenWali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKirim)
                    .addComponent(buttonReset))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Kirim Pesan", jPanel18);

        tabelPesanMasuk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelPesanMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Dari", "Isi Pesan", "Status", "Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPesanMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPesanMasukMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelPesanMasuk);

        textPesanMasuk.setColumns(20);
        textPesanMasuk.setRows(5);
        jScrollPane5.setViewportView(textPesanMasuk);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Hapus");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Hapus Semua");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pesan Masuk", jPanel16);

        tabelPesanTerkirim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelPesanTerkirim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kepada", "Isi Pesan", "Waktu"
            }
        ));
        tabelPesanTerkirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPesanTerkirimMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelPesanTerkirim);

        textPesanTerkirim.setColumns(20);
        textPesanTerkirim.setRows(5);
        jScrollPane7.setViewportView(textPesanTerkirim);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("Hapus Semua");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Hapus");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pesan Terkirim", jPanel17);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        tabPerwalian.addTab("Pesan", jPanel4);

        javax.swing.GroupLayout pengelolaanLayout = new javax.swing.GroupLayout(pengelolaan);
        pengelolaan.setLayout(pengelolaanLayout);
        pengelolaanLayout.setHorizontalGroup(
            pengelolaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPerwalian, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pengelolaanLayout.setVerticalGroup(
            pengelolaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengelolaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPerwalian)
                .addContainerGap())
        );

        content.add(pengelolaan, "PENGELOLAAN");

        footer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("@adinuralim");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout basedPanelLayout = new javax.swing.GroupLayout(basedPanel);
        basedPanel.setLayout(basedPanelLayout);
        basedPanelLayout.setHorizontalGroup(
            basedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
        );
        basedPanelLayout.setVerticalGroup(
            basedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basedPanelLayout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(basedPanel, java.awt.BorderLayout.CENTER);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(106, 40));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        masukMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        masukMenuItem.setText("Masuk");
        masukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(masukMenuItem);

        keluarMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        keluarMenuItem.setText("Keluar");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(keluarMenuItem);
        jMenu1.add(jSeparator1);

        tutupMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tutupMenuItem.setText("Tutup");
        tutupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(tutupMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutupMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupMenuItemActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Apkah yakin akan keluar?", "Konfirm", JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(1);
        }
    }//GEN-LAST:event_tutupMenuItemActionPerformed

    private void masukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukMenuItemActionPerformed
        // TODO add your handling code here:
        ((CardLayout) content.getLayout()).show(content, "MASUK");
    }//GEN-LAST:event_masukMenuItemActionPerformed

    private void buttonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMasukActionPerformed
        // TODO add your handling code here:
        masuk();
    }//GEN-LAST:event_buttonMasukActionPerformed

    private void buttonBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihkanActionPerformed
        // TODO add your handling code here:
        LoginController.getInstance().reset();
    }//GEN-LAST:event_buttonBersihkanActionPerformed

    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // TODO add your handling code here:
        ((CardLayout) content.getLayout()).show(content, "HOME");
        populateComponent(true);
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void buttonKontrakMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKontrakMatakuliahActionPerformed
        // TODO add your handling code here:
        KontrakDialog.getInstance(true).setVisible(true);
    }//GEN-LAST:event_buttonKontrakMatakuliahActionPerformed

    private void textSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSandiActionPerformed
        // TODO add your handling code here:
        masuk();
    }//GEN-LAST:event_textSandiActionPerformed

    private void textUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameActionPerformed
        // TODO add your handling code here:
        masuk();
    }//GEN-LAST:event_textUsernameActionPerformed

    private void buttonRinciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRinciActionPerformed
        // TODO add your handling code here:

        Matakuliah matakuliah = DetailMatakuliahController.getInstance().getMatakuliah();
        if (matakuliah != null) {
            DetailMatakuliahDialog.getInstance(matakuliah).setVisible(true);
        } else {
            Message.getInstance(this).runErrorMessage("pilih matakuliah!");
        }
    }//GEN-LAST:event_buttonRinciActionPerformed

    private void buttonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKirimActionPerformed
        // TODO add your handling code here:
        PesanController.getInstance().kirimPesan();
    }//GEN-LAST:event_buttonKirimActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:

        PesanController.getInstance().reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void tabelPesanMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPesanMasukMouseClicked
        // TODO add your handling code here:
        PesanController.getInstance().bacaPesanMasuk();
    }//GEN-LAST:event_tabelPesanMasukMouseClicked

    private void tabelPesanTerkirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPesanTerkirimMouseClicked
        // TODO add your handling code here:
        PesanController.getInstance().bacaPesanTerkirim();
    }//GEN-LAST:event_tabelPesanTerkirimMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(MainFrame.getInstance(), "Apakah yakin hapus pesan?", "Konfirm", JOptionPane.YES_NO_OPTION) == 0) {
            PesanController.getInstance().hapusPesanTerkirim();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(MainFrame.getInstance(), "Apakah yakin hapus semua pesan?", "Konfirm", JOptionPane.YES_NO_OPTION) == 0) {
            PesanController.getInstance().hapusSemuaPesanTerkirim();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(MainFrame.getInstance(), "Apakah yakin hapus pesan?", "Konfirm", JOptionPane.YES_NO_OPTION) == 0) {
            PesanController.getInstance().hapusPesanMasuk();
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(MainFrame.getInstance(), "Apakah yakin hapus semua pesan?", "Konfirm", JOptionPane.YES_NO_OPTION) == 0) {
            PesanController.getInstance().hapusSemuaPesanMasuk();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void comboTahunAkademikKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTahunAkademikKrsActionPerformed
        // TODO add your handling code here:

        int selected = comboTahunAkademikKrs.getSelectedIndex();

        if (selected > 0) {
            buttonKontrakMatakuliah.setEnabled(false);
        } else {
            buttonKontrakMatakuliah.setEnabled(true);
        }
    }//GEN-LAST:event_comboTahunAkademikKrsActionPerformed

    private void buttonCariKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariKrsActionPerformed
        // TODO add your handling code here:
        MahasiswaController.getInstance().populateDaftarKrs(LoginController.getInstance().getMahasiswa());
    }//GEN-LAST:event_buttonCariKrsActionPerformed

    private void buttonResetKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetKrsActionPerformed
        // TODO add your handling code here:
        try {
            comboTahunAkademikKrs.setSelectedIndex(0);
            MahasiswaController.getInstance().populateDaftarKrs(LoginController.getInstance().getMahasiswa());
        } catch (Exception e) {
            SplashLauncher.logger.log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_buttonResetKrsActionPerformed

    private void buttonMundurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMundurActionPerformed
        // TODO add your handling code here:
        PerwalianController.getInstance().updatePerwalian();
    }//GEN-LAST:event_buttonMundurActionPerformed

    private void buttonCetakKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakKrsActionPerformed
        // TODO add your handling code here:

        MahasiswaController.getInstance().krsPreview();
    }//GEN-LAST:event_buttonCetakKrsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                MainFrame.getInstance().setVisible(true);
            }
        });
    }

    //get component
    public JPasswordField getTextSandi() {
        return textSandi;
    }

    public JTextField getTextUsername() {
        return textUsername;
    }

    public JLabel getTextIpk() {
        return textIpk;
    }

    public JLabel getTextNama() {
        return textNama;
    }

    public JLabel getTextNpm() {
        return textNpm;
    }

    public JLabel getTextProdi() {
        return textProdi;
    }

    public JLabel getTextProgram() {
        return textProgram;
    }

    public JLabel getTextDosenWali() {
        return textDosenWali;
    }

    public JComboBox getComboTahunAkademikKrs() {
        return comboTahunAkademikKrs;
    }

    public JTable getTabelKrs() {
        return tabelKrs;
    }

    public JLabel getTextDosenKrs() {
        return textDosenKrs;
    }

    public JLabel getTextIpkKrs() {
        return textIpkKrs;
    }

    public JLabel getTextNamaKrs() {
        return textNamaKrs;
    }

    public JLabel getTextNpmKrs() {
        return textNpmKrs;
    }

    public JLabel getTextNpmKrs1() {
        return textNpmKrs1;
    }

    public JLabel getTextProdiKrs() {
        return textProdiKrs;
    }

    public JLabel getTextProgramKrs() {
        return textProgramKrs;
    }

    public JLabel getTextTotalSks() {
        return textTotalSks;
    }

    public JTable getTabelMatakuliah() {
        return tabelMatakuliah;
    }

    public JTextArea getTextPesan() {
        return textPesan;
    }

    public JLabel getTotalSksMahasiswa() {
        return totalSksMahasiswa;
    }

    public JLabel getTextPesanDosenWali() {
        return textPesanDosenWali;
    }

    public JTable getTabelPesanMasuk() {
        return tabelPesanMasuk;
    }

    public JTable getTabelPesanTerkirim() {
        return tabelPesanTerkirim;
    }

    public JTextArea getTextPesanMasuk() {
        return textPesanMasuk;
    }

    public JTextArea getTextPesanTerkirim() {
        return textPesanTerkirim;
    }

    public JLabel getTextIpsKrs() {
        return textIpsKrs;
    }

    public JLabel getTextStatus() {
        return textStatus;
    }

    public JButton getButtonCetakKrs() {
        return buttonCetakKrs;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basedPanel;
    private javax.swing.JButton buttonBersihkan;
    private javax.swing.JButton buttonCariKrs;
    private javax.swing.JButton buttonCetakKrs;
    private javax.swing.JButton buttonKirim;
    private javax.swing.JButton buttonKontrakMatakuliah;
    private javax.swing.JButton buttonMasuk;
    private javax.swing.JButton buttonMundur;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonResetKrs;
    private javax.swing.JButton buttonRinci;
    private javax.swing.JComboBox comboTahunAkademikKrs;
    private javax.swing.JPanel content;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JMenuItem keluarMenuItem;
    private javax.swing.JPanel masuk;
    private javax.swing.JMenuItem masukMenuItem;
    private javax.swing.JPanel pengelolaan;
    private javax.swing.JTabbedPane tabPerwalian;
    private javax.swing.JTable tabelKrs;
    private javax.swing.JTable tabelMatakuliah;
    private javax.swing.JTable tabelPesanMasuk;
    private javax.swing.JTable tabelPesanTerkirim;
    private javax.swing.JLabel textDosenKrs;
    private javax.swing.JLabel textDosenKrs1;
    private javax.swing.JLabel textDosenWali;
    private javax.swing.JLabel textIpk;
    private javax.swing.JLabel textIpkKrs;
    private javax.swing.JLabel textIpsKrs;
    private javax.swing.JLabel textNama;
    private javax.swing.JLabel textNamaKrs;
    private javax.swing.JLabel textNpm;
    private javax.swing.JLabel textNpmKrs;
    private javax.swing.JLabel textNpmKrs1;
    private javax.swing.JTextArea textPesan;
    private javax.swing.JLabel textPesanDosenWali;
    private javax.swing.JTextArea textPesanMasuk;
    private javax.swing.JTextArea textPesanTerkirim;
    private javax.swing.JLabel textProdi;
    private javax.swing.JLabel textProdiKrs;
    private javax.swing.JLabel textProgram;
    private javax.swing.JLabel textProgramKrs;
    private javax.swing.JPasswordField textSandi;
    private javax.swing.JLabel textStatus;
    private javax.swing.JLabel textTotalSks;
    private javax.swing.JTextField textUsername;
    private javax.swing.JLabel totalSksMahasiswa;
    private javax.swing.JLabel totalSksMahasiswa1;
    private javax.swing.JMenuItem tutupMenuItem;
    // End of variables declaration//GEN-END:variables
}
